
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tjm1999/wscbc-auth:0.1
          imagePullPolicy: IfNotPresent
          command:
            - "java" 
            - "-jar"
            - "authservice-0.0.1-SNAPSHOT.jar"
            - --spring.profiles.active=dev  
            - --spring.datasource.url=jdbc:mysql://mysql.default.svc:3306/web
          ports:
            - containerPort: 8080
              protocol: TCP
---
 apiVersion: v1
 kind: Service
 metadata:
   name: auth
 spec:
   ports:
     - name: auth-port
       protocol: TCP
       port: 8080
       targetPort: 8080
       nodePort: 31808
   type: NodePort
   selector:
     app: auth

