
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
spec:
  selector:
    matchLabels:
      app: url
  replicas: 1
  template:
    metadata:
      labels:
        app: url
    spec:
      containers:
        - name: url
          image: tjm1999/wscbc-url:0.1
          imagePullPolicy: IfNotPresent
          command:
            - "java" 
            - "-jar"
            - "urlservice-0.0.1-SNAPSHOT.jar"
            - --spring.profiles.active=dev  
            - --spring.datasource.url=jdbc:mysql://mysql.default.svc:3306/web
          ports:
            - containerPort: 8000
              protocol: TCP
---
 apiVersion: v1
 kind: Service
 metadata:
   name: url
 spec:
   ports:
     - name: url-port
       protocol: TCP
       port: 8000
       targetPort: 8000
       nodePort: 31800
   type: NodePort
   selector:
     app: url

